name 'fs-moodle'
maintainer 'steven pollock'
maintainer_email 'spollock@forescout.com'
license 'all_rights'
description 'Installs/Configures a Moodle LMS'
long_description 'Installs/Configures a Moodle LMS the Forescout way'
version '0.1.9'

depends 'apt',    '~> 4.0'
depends 'system', '~> 0.11'
depends 'ntp',    '~> 3.2.0'
depends 'mysql', '~> 8.0'
